apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-scraper-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask-scraper
  template:
    metadata:
      labels:
        app: flask-scraper
    spec:
      containers:
      - name: flask-scraper
        image: nancygarg999/flask_scraper_capstone_feb_2026:latest
        ports:
        - containerPort: 5500


# Local machine ---> Docker image --> Container --> Pod ---> K8s(minikube cluster)
# Docker container -> Inside a pod -> Pod has an ip -> external access thru port-forwarding.